config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :pics
  root "pics#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pic.rb
class Pic < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :pics
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
    before_action :find_pic, only: [:show, :edit, :update, :destroy]
    def index
        @pics = Pic.all.order('created_at DESC')
    end

    def new 
        @pic = current_user.pics.build
    end

    def create 
        @pic = current_user.pics.build(pic_params)
        if @pic.save
            redirect_to @pic, notice: "Yess! It was Posted"
        else
            render 'new'
        end
    end

    def show
    end

    def edit
    end

    def destroy
        @pic.destroy
        redirect_to root_path
    end

    def update
        if @pic.update(pic_params)
            redirect_to @pic, notice: "Update Succees"
        else
            render 'edit'
        end

    end


    private

    def find_pic
        @pic = Pic.find(params[:id])
    end

    def pic_params
        params.require(:pic).permit(:title, :description)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/layouts/application.html.haml
%html
  %head
    %title Instagramm
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = csrf_meta_tags
  %body
    -flash.each do|name, msg|
      = content_tag :div, msg, class: "alert alert-info"
    %p.notice= notice
    %p.alert= alert 

    = yield 

app/views/pics/_form.html.haml
= simple_form_for @pic, html: { multipart: true} do |f|
    - if @pic.errors.any?
        #errors
            %h2
                = pluralize(@pic.errors.count , "error")
                prevented this Pic From Saving
            %ul
                - @pic.errors.full_message.each do |msg|
                    %li= msg
                
    .form-group
        = f.input :title, input_html: {class: 'form-control'}
    .form_group
        = f.input :description, input_html: {class: 'form-control'}

    = f.button :submit, class: "btn btn-info"

app/views/pics/edit.html.haml
%h1
    Edit  Pic 

= render 'form'

= link_to "Cancel" , pic_path

app/views/pics/index.html.haml
%h1
    Placeholder

- @pics.each do |pic|
    %h1= pic.title
    %p= pic.description
    = link_to "Show" , pic

%br/

= link_to "New" , new_pic_path

app/views/pics/new.html.haml
%h1
    Post Pic 
= render 'form'

= link_to "Back" , root_path

app/views/pics/show.html.haml
%h1= @pic.title
%p= @pic.description
%p= @pic.user.email
= link_to "Back" , root_path
= link_to "Edit" , edit_pic_path
= link_to "Delete" , pic_path ,  method: :delete , data: {confirm: "Are You Sure? "}